### ISSUE TITLE
Code blocks seems to be broken (kind of)

### ISSUE THREAD

**Issue by JanLoebel** [CannerCMS/canner-slate-editor#7]
Hi there,

I have a very strange behaviour of the code block. I've captured a gif to show you what I mean:

![defect](https://user-images.githubusercontent.com/1765067/38042421-9e914032-32b4-11e8-9dbb-6f350e25162a.gif)

If i type ` for several times only some of them are converted to HTML and somehow backspace is broken after I get a code block.

I'm using a Mac Book Pro (10.13) with Chrome 65.

Best regards,
Jan

**Comment by Slapbox** [comment]
Maybe I'm doing something wrong, but can't reproduce this in Chrome on Windows 7. Can you outline exactly what input results in exactly what output?

**Comment by chilijung** [comment]
@JanLoebel this editor use regex to match for certain patterns. 

For inline code, the pattern matched is like

    `<your text>`

For code blocks, you will have to type three backticks follow with space.

    ```[space]

If you want specific language in the code block

    ```<lang>[space]

for example

    ```js[space]

to create a javascript code block.

-----

So in the gif in your issue, when you type two backticks and follow with text and then backticks, this does match inline code instead of code blocks.

For the backspace issue, I can't reproduce in my Chrome 65 either, maybe you could provide more information? Thanks!
